import React from "react";
import Link from "next/link";
import Head from "next/head";

import axiosClient from "../../libraries/axiosClient";

export default function ProductDetail(props) {
  const { products } = props;

  return (
    <>
      <Head>
        <title>Ban chai da nang</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>
        {
          products?.length > 0 && (
            products.map((item, idx) => <li key={item._id} className="mb-2">
              <Link href={`/products/${item._id}`}>
                <strong>{`${idx + 1}: ${item.name}`}</strong>
              </Link>
            </li>)
          )
        }
      </ul>
    </>
  );
}

// SSG
// export async function getStaticPaths() {
//   return {
//     paths: [],
//     fallback: true,
//   }
// }

export async function getStaticProps(content) {
  try {
    const response = await axiosClient.get('/products');

    return {
      props: {
        products: response.data,
      },
      revalidate: 5,
    };
  } catch (error) {
    return {
      notFound: true,
    };
  }
}
